language: php

php:
	- 5.5
	- 5.6

env:
    - SYMFONY_VERSION=2.5.*
    - SYMFONY_VERSION=2.6.*

before_script:
	- composer self-update
	- composer require symfony/symfony:${SYMFONY_VERSION}
    - composer update --dev



script: phpunit --coverage-text
